name = "dspx"
version = "1.0.2"
default_install_root = "~/zyng/apps/dspx/"
setup_venv = true
entrypoint = "src/app/main.py"
icon = "data/icons/dspx_og.png"
installer_dir = "dspx"

[source]
type = "git"
location = "https://github.com/WOLFBED/dspx"
sha256 = ""
gpg_key = ""
gpg_signature = ""

[required_apps]
apps = []
